"""empty message

Revision ID: c1ce5e3760e5
Revises: 5cca66045348
Create Date: 2020-11-26 10:10:30.812564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1ce5e3760e5'
down_revision = '5cca66045348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('quizs', sa.Column('content', sa.String(length=100), nullable=True))
    op.add_column('quizs', sa.Column('quiz_id', sa.Integer(), nullable=False))
    op.add_column('quizs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('quizs_ibfk_1', 'quizs', type_='foreignkey')
    op.create_foreign_key(None, 'quizs', 'users', ['user_id'], ['id'])
    op.drop_column('quizs', 'quizID')
    op.drop_column('quizs', 'userID')
    op.drop_column('quizs', 'problem')
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=True))
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'userID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userID', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'id')
    op.add_column('quizs', sa.Column('problem', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('quizs', sa.Column('userID', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('quizs', sa.Column('quizID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'quizs', type_='foreignkey')
    op.create_foreign_key('quizs_ibfk_1', 'quizs', 'users', ['userID'], ['userID'])
    op.drop_column('quizs', 'user_id')
    op.drop_column('quizs', 'quiz_id')
    op.drop_column('quizs', 'content')
    op.drop_table('stores')
    # ### end Alembic commands ###
