"""empty message

Revision ID: d06d9434a68d
Revises: 
Create Date: 2020-12-01 17:11:53.837434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06d9434a68d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userID', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('quizs',
    sa.Column('quizID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem', sa.String(length=100), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('userID', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('quizID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizs')
    op.drop_table('users')
    # ### end Alembic commands ###
