"""empty message

Revision ID: ef39222a6070
Revises: 
Create Date: 2020-11-11 13:14:25.263619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef39222a6070'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizs',
    sa.Column('quizID', sa.Integer(), nullable=False),
    sa.Column('problem', sa.String(length=100), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('quizID')
    )
    op.create_table('users',
    sa.Column('userID', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('quizs')
    # ### end Alembic commands ###
